import 'dart:convert';

String buildClientSetupScript(String slug, String clientName, String clientJson) {
  final date = DateTime.now().toIso8601String().substring(0, 10);
  return '''#!/bin/bash
# Project Setup Script — $clientName
# Generated by Raspucat on $date
# Requires: git (SSH access to github.com/Ras3uCat), Supabase CLI, python3

set -euo pipefail

TARGET="\$HOME/Documents/development/flutter_apps/clients/$slug"

if [ -d "\$TARGET" ]; then
  echo "✗ \$TARGET already exists — delete it first or choose a different slug."
  exit 1
fi

echo "→ Cloning modular_project template..."
git clone git@github.com:Ras3uCat/modular_project "\$TARGET"
rm -rf "\$TARGET/.git"
cd "\$TARGET"
git init
chmod +x execution/frontend/app/deliver.sh execution/frontend/app/prepare.sh 2>/dev/null || true

echo "→ Writing client.json..."
mkdir -p execution/frontend/app
cat > "execution/frontend/app/client.json" << 'CLIENT_JSON_EOF'
$clientJson
CLIENT_JSON_EOF

git add -A
git commit -m "scaffold: initial project for $slug"

echo ""
echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  ACTION REQUIRED — Create a Supabase project                 │"
echo "│                                                              │"
echo "│  1. Sign up at supabase.com with your provisioned email      │"
echo "│  2. Create a new project (free tier)                         │"
echo "│  3. Go to Settings → API and copy Project URL + anon key     │"
echo "└──────────────────────────────────────────────────────────────┘"
xdg-open "https://supabase.com/dashboard/sign-up" 2>/dev/null \\
  || open "https://supabase.com/dashboard/sign-up" 2>/dev/null \\
  || true
echo ""
read -rp "Press Enter when your Supabase project is ready... "

read -rp "Supabase Project URL:  " SUPABASE_URL
read -rp "Supabase Anon Key:     " SUPABASE_ANON_KEY
read -rsp "Raspucat Admin Token: " RASPUCAT_TOKEN
echo ""

PROJECT_REF=\$(echo "\$SUPABASE_URL" | sed 's|https://||' | sed 's|\\.supabase\\.co.*||')

echo "→ Patching client.json..."
python3 - << PYEOF
import json
with open('execution/frontend/app/client.json', 'r') as f:
    d = json.load(f)
d['SUPABASE_URL'] = '\$SUPABASE_URL'
d['SUPABASE_ANON_KEY'] = '\$SUPABASE_ANON_KEY'
d['RASPUCAT_ADMIN_TOKEN'] = '\$RASPUCAT_TOKEN'
with open('execution/frontend/app/client.json', 'w') as f:
    json.dump(d, f, indent=2)
PYEOF

echo "→ Linking Supabase CLI..."
cd execution/backend
supabase link --project-ref "\$PROJECT_REF"

# Report supabase_account_created to Raspucat
RASPUCAT_API=\$(python3 -c "import json; d=json.load(open('../frontend/app/client.json')); print(d.get('RASPUCAT_API',''))" 2>/dev/null || echo "")
RASPUCAT_QUOTE_ID=\$(python3 -c "import json; d=json.load(open('../frontend/app/client.json')); print(d.get('RASPUCAT_QUOTE_ID',''))" 2>/dev/null || echo "")
if [[ -n "\$RASPUCAT_API" && -n "\$RASPUCAT_QUOTE_ID" && -n "\$RASPUCAT_TOKEN" ]]; then
  curl -sf -X POST "\${RASPUCAT_API}/functions/v1/admin-delivery-progress" \\
    -H "Content-Type: application/json" \\
    -d "{\\"adminToken\\":\\"\$RASPUCAT_TOKEN\\",\\"quoteId\\":\\"\$RASPUCAT_QUOTE_ID\\",\\"action\\":\\"upsert\\",\\"step\\":\\"supabase_account_created\\",\\"checked\\":true,\\"checked_by\\":\\"system\\"}" \\
    2>/dev/null && echo "✓ supabase_account_created reported" || true
fi

echo "→ Running deliver.sh..."
cd ../frontend/app
./deliver.sh

echo ""
echo "✓ Done — check Raspucat admin for delivery progress"
''';
}

// Parses CLIENT_SLUG and CLIENT_NAME from a generated client.json string.
// Returns null for either if the JSON is malformed or the key is missing.
({String slug, String name}) parseClientMeta(String json) {
  try {
    final map = jsonDecode(json) as Map<String, dynamic>;
    return (
      slug: (map['CLIENT_SLUG'] as String?) ?? 'client',
      name: (map['CLIENT_NAME'] as String?) ?? 'Client',
    );
  } catch (_) {
    return (slug: 'client', name: 'Client');
  }
}
